- name: Install nfs-server man
  hosts: all
  become: yes
  # vars:
  #   ahmed_password:  "ahmed"
  #   ahmed2_password: "ahmed2"
  tasks: 
  - name: installing  packages
    vars:
      ansible_python_interpreter: /usr/bin/python3
    yum:
      name:
      - python
      - python3
      - vim
      - firewalld                           
      - bash-completion.noarch
      - nfs-utils
      update_cache: yes
      state: present
  - name: making some alias
    ansible.builtin.blockinfile:
      path: /etc/bashrc
      block: |
        alias c=clear
        alias k=kubectl 
        alias la='ls -lahF'
  - name: Set a hostname
    ansible.builtin.hostname:
      name: nfs-server               
  - name: start & enable nfs-server
    systemd: 
      name: nfs-server 
      state: started
      enabled: true         
  - name: start & enable firewalld
    systemd: 
      name: firewalld
      state: started
      enabled: true        
  - name: permit traffic in the default zone for nfs service
    ansible.posix.firewalld:
      service: nfs
      permanent: true
      state: enabled
  - name: permit traffic in the default zone for mountd service
    ansible.posix.firewalld:
      service: mountd
      permanent: true
      state: enabled
  - name: permit traffic in the default zone for rpc-bind service
    ansible.posix.firewalld:
      service: rpc-bind
      permanent: true
      state: enabled
  - name: Reload service firewalld
    ansible.builtin.systemd:
      name: firewalld.service
      state: restarted  
  - name: Create /share directory if it does not exist
    ansible.builtin.file:
      path: /share
      state: directory
      mode: "0777"
  - name: configure /etc/exports file man
    ansible.builtin.blockinfile:
      path: /etc/exports
      block: |
        /share    *(rw,no_root_squash)   
  # - name: Ensure required entries are made to hosts file. # Notes 1232
  #   lineinfile:
  #     path: /etc/exports
  #     state: present
  #     line: "{{ item }}"
  #   with_items:
  #     - '/export/volumes  *(rw,no_root_squash,no_subtree_check,insecure)'              
  - name: Re-export the share
    command: exportfs -rav
