- name: play-1 Install python3 & docker 
  #hosts: my_ec2
  hosts: all
  become: yes
  tasks: 
  - name: play-1--task-1 install docker 
    vars:
      ansible_python_interpreter: /usr/bin/python
    yum:
      name:
      - python
      - python3
      - pip
      - podman-docker
      update_cache: yes
      state: present
  - name: making some alias
    ansible.builtin.blockinfile:
      path: /etc/bashrc
      block: |
        alias c=clear
        alias k=kubectl          
  - name: Install docker-compose
    vars:
      ansible_python_interpreter: /usr/bin/python
    get_url: 
      #url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
      url: https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-linux-x86_64 
      dest: /usr/local/bin/docker-compose
      mode: +x
  - name: start & enable podman 
    systemd: 
      name: podman
      state: started
      enabled: true
  - name: Ensure docker group exits
    group:
      name: docker
      state: present         
  - name: Add ec2-user to docker group
    user: 
      name: ec2-user
      groups: docker 
      append: yes
  - name: Reconnect to server session
    meta: reset_connection
  - name: Copy docker compose file 
    copy:
      src: /home/ahmed/Desktop/terraform/general-project-beta/ec2-docker/docker-compose-gp.yaml
      dest: /home/ec2-user/docker-compose.yaml
  - name: Grant user ec2-user use docker 
    ansible.posix.acl:
      path: /var/run/podman/
      entity: ec2-user
      etype: user
      permissions: rwx
      state: present
      # default: true
      recursive: true
      follow: true
    register: acl_info
  - name: output the register variable value
    debug:
      msg: 
      - "the acl_info register =  {{acl_info}} "      

# To make pip install ==> you must be not root man

- name: Test docker pull
  #hosts: my_ec2
  hosts: all
  tasks:
  - name: Install docker python3 module
    vars:
      ansible_python_interpreter: /usr/bin/python3
    pip: 
      name: 
      - docker
      - docker-compose      
  - name: Install docker python2 module
    vars:
      ansible_python_interpreter: /usr/bin/python
    pip: 
      name: 
      - docker==4.4.4         
      - docker-compose
  - name: docker login
    vars:
      ansible_python_interpreter: /usr/bin/python
    docker_login:
      registry_url: https://index.docker.io/v1/
      username: 9529777
      password: ahmed@12345  
  - name: Start docker container from docker-compose
    vars:
      ansible_python_interpreter: /usr/bin/python  
    docker_compose: 
      project_src: /home/ec2-user
      state: present        # docker-compose up
      #state: absent        # docker-compose down

    